# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20171025_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('f', 'Facebook'), ('d', 'Django')], max_length=1),
        ),
    ]
